### ISSUE TITLE
Main content of window does not load after logging in

### ISSUE THREAD

**Issue by dinoboy197** [tiliado/nuvola-app-google-play#1]
**This bug report has been forwarded to [the WebKitGTK+ bug tracker](https://bugs.webkit.org/show_bug.cgi?id=140430).**

Reason: It is reproducible in the WebKiGTK+ MiniBrowser debugging tool, so it's likely a bug in the WebKitGTK+ library rather than in Nuvola Player.

Google Play works great for me in a standalone browser on my system (Chrome, Firefox, etc).

However, when I use Nuvola Player 3 the Google Play page content never loads. When I start Nuvola Player 3, I select Google Play Music as my service of choice, and am presented with a login window. I log in using my Google credentials, and then am taken to a partially loaded Google Music window.

Waiting for a few minutes doesn't help, nor does reloading the page with the reload button, nor does restarting the app. Clicking on any of the links in the sidebar (My Library, etc) doesn't help either.

Here is a screenshot of what I see after I log in:

![image](https://cloud.githubusercontent.com/assets/631178/5414758/75059a7a-81d6-11e4-84b5-a3a28c953f5c.png)

Using:
* nuvolaplayer3: 3.0.0~201412120701.7517854-0+1~trusty
* libdiorite: 0.1.0~201412111927.93a0ec0-0+1~trusty
* nuvolaplayer3-google-play-music: 5.0-1~trusty
* flashplugin-installer: 11.2.202.425ubuntu0.14.04.1

**Comment by dinoboy197** [comment]
Hey, have been away for a few weeks. Just filed the bug report here: https://bugs.webkit.org/show_bug.cgi?id=140430

**Comment by fenryxo** [comment]
Thank you, the bug report is great :-)

**Comment by fenryxo** [comment]
I've added this issue to the [Known Issues](https://github.com/tiliado/nuvola-app-google-play/wiki/Known-Issues) wiki page and I'm closing this ticket as it has been forwarded upstream and cannot do more with it.
